# Generated by Django 3.0.3 on 2020-02-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Pizza')),
                ('description', models.TextField(verbose_name='descriptions')),
                ('rating', models.FloatField(default=0, verbose_name='Rating')),
                ('url', models.URLField(verbose_name='Internet-address Pizza')),
            ],
        ),
    ]
