# Generated by Django 3.0.3 on 2020-02-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20200214_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzashop',
            options={'verbose_name': 'Pizzaplace', 'verbose_name_plural': 'PizzaPlaces'},
        ),
    ]
