# Generated by Django 3.0.3 on 2020-02-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20200214_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzashop',
            options={},
        ),
    ]
